### ISSUE TITLE
Build for production failed

### ISSUE THREAD

**Issue by heinerlamprecht** [ngstack/translate#1]
When build an app for production with `ng build --prod`, the following error is thrown:

`ERROR in Error during template compile of 'AppModule' Function calls are not supported in decorators but 'TranslateModule' was called.`

Reason is the `forRoot()` call in the declaration of the main module.

**Comment by DenisVuyka** [comment]
@heinerlamprecht thanks for the feedback. I will try to fix the issue shortly.

**Comment by DenisVuyka** [comment]
@heinerlamprecht please see the new 0.5.0 version. Now should support production mode and AoT, but requires extra setup in the app module (see readme)

```
export function setupTranslateService(service: TranslateService) {
  return () => service.load();
}
```

**Comment by heinerlamprecht** [comment]
@DenisVuyka I updated to 0.5.0 and everything works like a charm.  Thanks for the fast response.
