### ISSUE TITLE
Compile failed because of unknown pipe

### ISSUE THREAD

**Issue by heinerlamprecht** [ngstack/translate#11]
I'm using ngstack/translate in an Angular/Ionic project.   Although the application works, I do get errors in the IDE (IntelliJ), telling me that the pipe "translate" in unknown.

Now I tried the new Ivy renderer and do get the same error messages:

`ERROR in : Template parse errors:
The pipe 'translate' could not be found ("<ion-header>
    <ion-toolbar>
        <ion-title>{{[ERROR ->]'Edit' | translate}}</ion-title>
    </ion-toolbar>
</ion-header>`

I can ignore the IDE warnings, although they are annoying.  But it would be very nice to be able to use the upcoming Angular compiler.

Thanks in advance,  Heiner

**Comment by DenysVuika** [comment]
I can't say anything for the IntelliJ as I am not using it. Might be the IDE problem detecting the pipes.  The project works fine with Angular 7 and Visual Studio Code. 

The Ivy compiler is not out yet but I will for sure review and update the code if needed, once Ivy is stable enough.
