### ISSUE TITLE
HttpInterceptor not triggering with lazy loaded modules

### ISSUE THREAD

**Issue by micobarac** [ngstack/translate#14]
Custom `HttpInterceptor` not triggering with lazy loaded modules, when using `TranslateModule` as stated in docs.

It's a complex project, so I cannot show the example code.

The problem with lazy loaded modules and `HttpInterceptor` is that `HttpClientModule` can only be imported once in the project inside `app.module.ts`. Looking into this library's code, I found that `HttpClientModule` is imported internally, which, I presume, could cause this problem.

The files to look for these imports are:

[projects/translate/src/lib/translate.module.ts](https://github.com/ngstack/translate/blob/292cb2443863a49b8104f541d2b55512dd178efb/projects/translate/src/lib/translate.service.spec.ts)
[projects/translate/src/lib/translate.pipe.spec.ts](https://github.com/ngstack/translate/blob/0c466fd7a8a0b2fbb9c6e3ddeca43bd38446880e/projects/translate/src/lib/translate.pipe.spec.ts)
[projects/translate/src/lib/title.service.spec.ts](https://github.com/ngstack/translate/blob/7c44f546f1626a68b840821b286d4d3a4fd0d041/projects/translate/src/lib/title.service.spec.ts)
[projects/translate/src/lib/translate.service.spec.ts](https://github.com/ngstack/translate/blob/292cb2443863a49b8104f541d2b55512dd178efb/projects/translate/src/lib/translate.service.spec.ts)

**Comment by DenysVuika** [comment]
Yes, makes sense. While TranslateService is provided in the root, the lazy module makes a copy of HttpClientModule and corresponding providers if any.

Thanks for reporting, I will try to fix this issue and move HttpClientModule to the app level.

**Comment by micobarac** [comment]
As the library requires that `HttpClientModule` should be imported in `app.module.ts`, `HttpClientModule` imports should be removed from all the internal files.

**Comment by DenysVuika** [comment]
@micobarac the unit tests are fine, those need to import HTTP module into the TestBed. Feel free to check this PR and see if that fixes your issue: https://github.com/ngstack/translate/pull/15

**Comment by micobarac** [comment]
@DenysVuika I have tried the commit you suggested and it still doesn't work. I think that you haven't removed `HttlClientModule` from all files but `app.module.ts`. Can you please check it again? Thanks.

**Comment by DenysVuika** [comment]
The 1.2 is not published to NPM yet. I removed the file from module but leaving in unit tests, those have nothing to do with your application.

**Comment by micobarac** [comment]
I added the latest commit from the git repository, not from NPM.

**Comment by DenysVuika** [comment]
I may need some example to reproduce the issue. So far the library code has no direct imports of the HttpClientModule if you check the repo.

**Comment by micobarac** [comment]
Perhaps I haven't imported the latest commit well. How do I do it with Yarn, using Git commit?

**Comment by DenysVuika** [comment]
I am publishing 1.2.0 right now, you will be able to check in a while directly from NPM

**Comment by micobarac** [comment]
Ok, thanks :)

**Comment by DenysVuika** [comment]
1.2.0 is out: https://www.npmjs.com/package/@ngstack/translate/v/1.2.0

**Comment by micobarac** [comment]
I have tried the 1.2.0 version from NPM and it works like a charm.

Thanks a lot.
