### ISSUE TITLE
Problem with using parameters

### ISSUE THREAD

**Issue by micobarac** [ngstack/translate#17]
This is my translation file's content:

```json
"AccessDenied": {
  "Title": "Access Denied",
  "Message": "Access is denied to user {name}!"
}
```

This works:

```html
<div class="page">
    <span class="logo"></span>
    <h1>{{'AccessDenied.Title' | translate}}</h1>
    <p>{{'AccessDenied.Message' | translate:{ 'name': account.name } }}</p>
</div>
```

This doesn't (no space after param closing curly bracket):

```html
<div class="page">
    <span class="logo"></span>
    <h1>{{'AccessDenied.Title' | translate}}</h1>
    <p>{{'AccessDenied.Message' | translate:{ 'name': account.name }}}</p>
</div>
```

Error thrown by Angular compiler:

`Parser Error: Missing expected } at the end of the expression [{{'AccessDenied.Message' | translate:{ 'name': account.name }}}]`

This looks like more like an Angular limitation or a bug.

Also, this should be working to, but currently, it's not (added spaces around param for readability):

```json
"AccessDenied": {
  "Title": "Access Denied",
  "Message": "Access is denied to user { name }!"
}
```

Result:

`Param name is not translated.`

I presume that some trimming should be executed when parsing params.

Also, when passing param object, single quoting the param name is not necessary, as we are passing an object.

So, this:

```html
<p>{{'AccessDenied.Message' | translate:{ 'name': account.name } }}</p>
```

can be written like this (no quotes):

```html
<p>{{'AccessDenied.Message' | translate:{ name: account.name } }}</p>
```

**Comment by DenysVuika** [comment]
With the curly brackets, I believe this is Angular thing, at list my linter starts complaining if there's no space, i.e.

works
```
{{ 'FORMATTED.HELLO_MESSAGE' | translate: { username: 'world' } }}
```

complains:
<img width="572" alt="screenshot 2019-02-23 at 10 56 13" src="https://user-images.githubusercontent.com/503991/53285554-a7e60f00-3759-11e9-86d2-933400d2377b.png">

**Comment by DenysVuika** [comment]
For the second part, the curly braces inside JSON is not Angular expressions, those are supported and replaced by the TranslationService, the regex does not support spaces right now: https://github.com/ngstack/translate/blob/master/projects/translate/src/lib/translate.service.ts#L317
