### ISSUE TITLE
Support for routes

### ISSUE THREAD

**Issue by Bullace** [ngstack/translate#2]
Hello,
Do you have any plans on supporting routes? I'm looking for an alternative for localize-router since it seems abandoned and has a bunch of bugs. Just wondering if I should keep an eye open for changes to this project.

**Comment by DenisVuyka** [comment]
@Bullace you mean enforcing locale based on the language fragment, like `/en/something` ?

**Comment by Bullace** [comment]
Yes, and then also translating the routes themselves.

[localize-router](https://github.com/Greentube/localize-router) linky so you can check that out in case you didn't know about that yet (it's an ngx-translate extension).

For some reason it hasn't been updated yet for Angular/RXJS 6, I'm currently using someones fork but that also has issues and the maintainers just seem to have vanished. Was already looking into fixing it myself but it's a bit above my skill level :/

**Comment by DenisVuyka** [comment]
@Bullace I will take a look, thanks.
