### ISSUE TITLE
Angular 8 support?

### ISSUE THREAD

**Issue by micobarac** [ngstack/translate#21]
Angular 8 is out there. Is Angular 8 support planned any time soon, or should I create a fork?

**Comment by DenysVuika** [comment]
Planned but you can create a pull request instead of a fork.

**Comment by micobarac** [comment]
Can you please add me to collaborators as I do not have sufficient permissions to create pull request right now?

**Comment by DenysVuika** [comment]
Ah yes, sorry. I think easier would be to fork and then create a PR if everything works ok for you locally.

**Comment by micobarac** [comment]
I've already cloned your original project, as you've suggested, made changed and tested. All seems to work fine.

**Comment by micobarac** [comment]
I've created a new branch, with master unchanged.

**Comment by micobarac** [comment]
Shall I create fork and do it all over again?

**Comment by DenysVuika** [comment]
You should be able to collaborate now, thanks.

**Comment by micobarac** [comment]
I've also added a CHANGELOG.md file, which should be filled for earlier versions you've made.

**Comment by micobarac** [comment]
![image](https://user-images.githubusercontent.com/16001837/59507946-b4c77380-8eac-11e9-8fe0-ca40668cb0a5.png)

**Comment by DenysVuika** [comment]
You may need to accept invitation: https://github.com/ngstack/translate/invitations

**Comment by micobarac** [comment]
Ah, ok thanks :)

**Comment by micobarac** [comment]
I've pushed the new branch angular8 successfully. I hope it's ok.

**Comment by DenysVuika** [comment]
Thanks a lot! You can create a PR for the master, and I will try to review it as soon as possible

**Comment by micobarac** [comment]
In the root package.json there was a version 0.0.0. I've changed it to 1.2.2. I hope that was ok to change.

**Comment by DenysVuika** [comment]
The one that goes to NPM is here: https://github.com/ngstack/translate/blob/master/projects/translate/package.json

**Comment by micobarac** [comment]
I know that, I've upgraded also that one for the NPM, but this root one should reflect the latest version too. At least it's a good practice.

**Comment by DenysVuika** [comment]
I agree, thanks.
