### ISSUE TITLE
Emit activeLangChanged always when activeLang is changed

### ISSUE THREAD

**Issue by micobarac** [ngstack/translate#226]
When I set active language:

```typescript
translateService.activeLang = 'en';
```

How do I make `translateService.activeLangChanged` trigger, whenever the active language is set, no matter if it stayed the same?

**Comment by DenysVuika** [comment]
Not sure why you need that, but `activeLangChanged` is an EventEmitter, you can emit events manualy

**Comment by micobarac** [comment]
Well. I persist active language in Akita store. On app init, I load language from local storage, if, any, then I set the value to the store and `translateService.activeLang`. I can easily track changes in store, but, I cannot sync it with `translateService.activeLangChanged`. This is important for translating phrases inside typescript code, after the language file has been loaded.

**Comment by micobarac** [comment]
I solved it like this:

```typescript
import { Injectable } from '@angular/core';
import { Query } from '@datorama/akita';
import { TranslateService } from '@ngstack/translate';
import { startWith } from 'rxjs/operators';
import { Language } from './language.model';
import { LanguageState, LanguageStore } from './language.store';

@Injectable({
  providedIn: 'root'
})
export class LanguageQuery extends Query<LanguageState> {
  language$ = this.select(state => state.language);
  activeLanguage$ = this.translateService.activeLangChanged.pipe(startWith(this.translateService.activeLang));

  get language(): Language {
    return this.getValue().language;
  }

  constructor(protected store: LanguageStore, protected translateService: TranslateService) {
    super(store);
  }
}
```
