### ISSUE TITLE
Wrong version number

### ISSUE THREAD

**Issue by heinerlamprecht** [ngstack/translate#23]
Hi,

the version 1.2.2 is not backwards-compatible anymore due to the upgrade to Angular 8.

**Comment by DenysVuika** [comment]
Yes, sorry about that. I will do the major version upgrade and will pull the 1.2.2 from NPM

**Comment by DenysVuika** [comment]
Sorry about that. I suggest pinning the version to 1.2.1, should be already in your package-lock file. I have released 2.0.0 meanwhile and will stick to semver next time
