### ISSUE TITLE
Unable to set translationRoot in TranslateModule.forChild()

### ISSUE THREAD

**Issue by HangLoop** [ngstack/translate#3]
.forChild() expected 0 arguments.

Anyway to load another json file in lazy load module?

**Comment by DenisVuyka** [comment]
not for the moment. The main difference compared to ngx-translate is that this library has all translations resolved before the app is loaded. That helps solve tones of issues with async, observables and flickering.

**Comment by HangLoop** [comment]
How about changing the translationRoot or push new path to translatePaths after the app is init?

**Comment by HangLoop** [comment]
The main purpose is to point to a different translation file(.json) when navigate to a lazy load module.

**Comment by DenysVuika** [comment]
I suggest loading those with the main application to avoid the async load nightmare (especially waiting till stuff resolves). You will be able to reduce the amount of http calls even more if you merge locales together in production. After all, I believe you are not going to have megabytes of text in the lazy .json to need the separate loading?

However, if you know how to load those without "side effects", a PR would be appreciated.
