### ISSUE TITLE
Angular 9 support?

### ISSUE THREAD

**Issue by micobarac** [ngstack/translate#308]
It would be nice to have Angular 9 support:

```
warning " > @ngstack/translate@2.3.2" has incorrect peer dependency "@angular/common@^8.0.1".
warning " > @ngstack/translate@2.3.2" has incorrect peer dependency "@angular/core@^8.0.1".
```

**Comment by DenysVuika** [comment]
Yes, I will add Angular 9 support soon.

**Comment by sriten** [comment]
Hello, is there any update yet?

**Comment by DenysVuika** [comment]
Working on that right now, hope to have it finished tonight or tomorrow.

**Comment by DenysVuika** [comment]
Version 3.0.0 with the Angular 9 support is out. Please check it and issues if any.

**Comment by sriten** [comment]
Cheers @DenysVuika! I have upgraded and tested, it works as expected with angular 9. Awesome stuff!
