### ISSUE TITLE
[QUESTION] Library-Monorepo problem

### ISSUE THREAD

**Issue by mailok** [ngstack/translate#82]
Thank you very much for this project, it is very good.

I have a question, how could I use in @ngstack/translate a library, and use that library in an application that also uses @ngstack/translate?

This library can be lazy loaded or it can be loaded normally. I wish it could work for both cases.
Of course, this use case is a common when you use Monorepo in your company.
I also have the need for the library to be publishable, so it should have its own translation

**Comment by DenysVuika** [comment]
You should be using it like any other regular Angular library. If you are building another library, you can just install `@ngstack\translate` as a peer dependency and have the main application reference it as a regular dependency.

There's nothing special here in terms of the configuration

**Comment by mailok** [comment]
@DenysVuika  The problem is that the library should encapsulate its own translation service, and the application should also encapsulate its own translation service, so how would the library know when to change the language?
When a library loads lazy loading, it has its own injector, but when it loads normally it shares the translation service with that of the application where it is used.

Do you understand my problem ?, I do not know when my library will be loaded lazy loading or normal?

**Comment by DenysVuika** [comment]
This library supports standard Angular lazy loading. The service is provided in the root only, the pipe handles the translations. Library also supports multiple files, so you can put the extra strings coming with your library to the assets, or even configure angular.json to do that.

I don't really understand what is the problem here for your scenario.

**Comment by mailok** [comment]
@DenysVuika  Imagine that I want to publish my library and use it in an application that does not have translation services. So I would have to tell the library that it will be used with a specific language. What will not do changing. 

Now, another person uses the same library in another application where there is a translation service different from @ ngstack/translate, But still, I know that I have to tell the library to use the language that the application has configured.

These two cases tell me, that the library must have its own translation service, and its json files with the translations.

And this works great if that library is loaded in a lazy way, but if, it is loaded in the application in a normal way, then I would share the same translation service of the palication, and that is my problem.

I want the library to always have its own translation service injector, but I cannot achieve this if it is loaded normally in the application.

Sorry, I don't know English and I can hardly explain myself.

**Comment by DenysVuika** [comment]
If you want your child libraries support ngstack/translate, then both main application and your libraries should reference it, no matter lazy loaded or not. the translation data should be coming from the parent application. 

As soon as parent application triggers the language change - the `translate` pipe should translate the stuff everywhere.

Closing this ticket for now as it seems we are turning the issue tracker into the chat, not really addressing a particular problem.
