### ISSUE TITLE
Angular v13 support

### ISSUE THREAD

**Issue by kaname-png** [ngstack/translate#856]
Will this package continue to be updated?

**Comment by kaname-png** [comment]
Well, I think this project is abandoned

**Comment by DenysVuika** [comment]
@kaname-png the project is not abandoned, I will upgrade the library as soon as I find some free time for that

**Comment by DenysVuika** [comment]
Version 7.0.0 is out with Angular 13 upgrade: https://github.com/ngstack/translate/releases/tag/v.7.0.0
