### ISSUE TITLE
Multiple files per language

### ISSUE THREAD

**Issue by micobarac** [ngstack/translate#9]
Is it possible to split a single language translation file into multiple .json files (per module or component)?

Single language file can get really huge for big apps and difficult to maintain.

Setting .json file to be loaded dynamically in routes would be an extra feature.

**Comment by DenysVuika** [comment]
Not for the moment. I'm still investigating what is the easiest way to support file splitting and lazy loading. Mind that trying to split on per-component basis is opening a can of worms. At some point you may need to wait for numerous files downloaded just to show text correctly. Same for switching languages - there will be a performance/bandwidth penalty in this case.

**Comment by DenysVuika** [comment]
@micobarac yes, I fully agree that it lacks the per-module splitting and elaborating on that. thanks for the feeback :)
